# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d24edd15d9ba443f3bfc4d2c0cf70fe2af46d3b658defe60a86596106b181030a94d2783e6b6405501aae887907ed3a2d956051fc74fb0315bfdb666254a760

test:
  secret_key_base: 4b704167d2c94aa0a66fa081c0265cf30837ba3068249caf61efef31e412a3ce5a798230e79dd90c693c1f1edaab5dd733284af5f87029a4be92ab3d2cd4a689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
